name: RaviBala
favicon: null
layout_spectrum: 0.3157217879779637
typography_spectrum: 0.431924341712147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5194097878411412
  lightness: 0.0663417016621679
  saturation: 0.07201057113707066
  rhythmicContrast: 0.29050960042513907
purpose: []
